# Generated by Django 5.2.4 on 2025-09-16 06:00

import containers.models.container_label_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(default='默认容器名', verbose_name='容器名称')),
                ('container_type', models.CharField(choices=[('display', '只展示'), ('interactable', '只互动'), ('both', '同时'), ('hide', '隐藏')], default='display', verbose_name='容器类型')),
                ('container_meta', models.CharField(default='', verbose_name='元数据')),
                ('used_in_character', containers.models.container_label_field.ContainerCharacterField(default='None', verbose_name='所属角色模板')),
                ('label_1', containers.models.container_label_field.ContainerLabelField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='labels.examplelabel1', verbose_name='ExampleLabel1')),
                ('label_2', containers.models.container_label_field.ContainerLabelField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='labels.examplelabel2', verbose_name='ExampleLabel2')),
            ],
            options={
                'verbose_name': 'Example container',
                'verbose_name_plural': 'Example container',
            },
        ),
    ]
