# Generated by Django 5.2.4 on 2025-09-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancehashtable',
            options={'verbose_name': 'Instance Hash Table', 'verbose_name_plural': 'Instance Hash Table'},
        ),
    ]
