# Generated by Django 5.2.4 on 2025-09-16 06:00

import labels.models.label_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleLabel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', labels.models.label_field.LabelChoiceField(choices=[('timer', '计时器'), ('counter', '步进器'), ('read_only', '只读')], default='read_only', help_text='在网页展示时，若为计时器或步进器，且标签所在容器类型为"可互动"时，该标签触发器的API将会被调用', verbose_name='标签类型')),
                ('label_display_format', labels.models.label_field.LabelDisplayFormatField(default='<标签名>: <分隔><标签值>', help_text='在网页展示时，"<标签名>"和"<标签值>"会被替换为实际的值，使用"<分隔>"来实现分组，由"<分隔>"引导的组间距离由系统决定，"<分隔>"最多只能出现两次。默认为： <标签名>: <标签值>', verbose_name='标签值展示格式')),
                ('used_in_container', labels.models.label_field.LabelsContainerField(default='None', help_text='用于防止标签被跨模型重复使用，该值由系统自动管理，非必要情况请勿修改此值', verbose_name='所属容器')),
                ('label_name', labels.models.label_field.LabelNameField(default='ExampleLabel1', verbose_name='标签名称')),
                ('label_value', labels.models.label_field.LabelIntegerField(verbose_name='标签值')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleLabel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', labels.models.label_field.LabelChoiceField(choices=[('timer', '计时器'), ('counter', '步进器'), ('read_only', '只读')], default='read_only', help_text='在网页展示时，若为计时器或步进器，且标签所在容器类型为"可互动"时，该标签触发器的API将会被调用', verbose_name='标签类型')),
                ('label_display_format', labels.models.label_field.LabelDisplayFormatField(default='<标签名>: <分隔><标签值>', help_text='在网页展示时，"<标签名>"和"<标签值>"会被替换为实际的值，使用"<分隔>"来实现分组，由"<分隔>"引导的组间距离由系统决定，"<分隔>"最多只能出现两次。默认为： <标签名>: <标签值>', verbose_name='标签值展示格式')),
                ('used_in_container', labels.models.label_field.LabelsContainerField(default='None', help_text='用于防止标签被跨模型重复使用，该值由系统自动管理，非必要情况请勿修改此值', verbose_name='所属容器')),
                ('label_name', labels.models.label_field.LabelNameField(default='ExampleLabel2', verbose_name='标签名称')),
                ('label_value', labels.models.label_field.LabelIntegerField(verbose_name='标签值')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'abstract': False,
            },
        ),
    ]
