# Generated by Django 5.2.4 on 2025-09-16 06:00

import characters.models.character_container_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='默认角色名', verbose_name='角色名')),
                ('container', characters.models.character_container_field.CharacterContainerField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='containers.examplecontainer', verbose_name='ExampleContainer')),
                ('user', characters.models.character_container_field.CharacterUserField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_character', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'ExampleCharacter',
                'verbose_name_plural': 'ExampleCharacter',
            },
        ),
    ]
