# Generated by Django 5.2.4 on 2025-09-16 06:14

import characters.models.character_container_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplecharacter',
            name='character_name',
            field=models.CharField(default='default name', verbose_name='default name'),
        ),
        migrations.AlterField(
            model_name='examplecharacter',
            name='user',
            field=characters.models.character_container_field.CharacterUserField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_character', to=settings.AUTH_USER_MODEL, verbose_name='belongs to'),
        ),
    ]
