# Generated by Django 5.2.4 on 2025-09-16 06:14

import containers.models.container_label_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplecontainer',
            name='container_meta',
            field=models.CharField(default='', verbose_name='Meta data'),
        ),
        migrations.AlterField(
            model_name='examplecontainer',
            name='container_name',
            field=models.CharField(default='default name', verbose_name='default name'),
        ),
        migrations.AlterField(
            model_name='examplecontainer',
            name='container_type',
            field=models.CharField(choices=[('display', 'display'), ('interactable', 'interactable'), ('both', 'both'), ('hide', 'hide')], default='display', verbose_name='container type'),
        ),
        migrations.AlterField(
            model_name='examplecontainer',
            name='used_in_character',
            field=containers.models.container_label_field.ContainerCharacterField(default='None', verbose_name='belongs to'),
        ),
    ]
